apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-deploy
  template:
    metadata:
      labels:
        app: node-deploy
    spec:
      containers:
        - name: node-deploy-container
          image: nn09/node-deploy-img:latest
          ports:
            - containerPort: 3000
